### PR TITLE
Use new template lib

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by donny-dont** [comment]
@tboerger I’m assuming this is dependent on the previous PR

**Comment by tboerger** [comment]
@donny-dont what do you mean? there is no other pr :)

**Comment by donny-dont** [comment]
Sorry I’m losing track of what PRs are where whenever you do these mass updates

**Comment by tboerger** [comment]
Hehe, sorry... Just adding the template lib to all repos that should use it :)

**Pull request merged**
